version: "3.3"
services:

  proxy:
    image: sh1nd3l/proxy:0.1
    container_name: proxy
    ports:
      - "80:80"

  backend:
    image: sh1nd3l/flask-server:0.5
    container_name: flask

  redis:
    image: redis:7.0.4
    container_name: redis

  dnmonster:
    image: amouat/dnmonster
    container_name: dnmonster

  logspout:
    image: amouat/logspout-logstash
    container_name: logspout
    restart: always
    depends_on:
      logstash:
        condition: service_started
    ports:
      - "8000:90"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: logstash://logstash:5000

  logstash:
    image: logstash:6.4.0
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    container_name: logstash
    environment:
      LOGSPOUT: ignore
    ports:
      - "5000:5000"
    restart: always