version: "3.3"
#services:
#  proxy:
#    image: amouat/proxy:1.0
#    links:
#      - server
#    ports:
#      - "80:80"
#    environment:
#      - NGINX_HOST=127.0.0.1
#      - NGINX_PROXY=http://127.0.0.1:8080
#  server:
#    image: sh1nd3l/flask-server:0.5
#    environment:
#      - "ENV=PROD"
#    links:
#      - redis
#      - dnmonster
#  redis:
#    image: redis:7.0.4
#  dnmonster:
#    image: amouat/dnmonster
#  logstash:
#    image: amouat/logspout-logstash
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock
#    ports:
#      - "8080:90"

services:
  proxy:
    image: amouat/proxy:1.0
    links:
      - identidock
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PROXY=http://identidock:9090
  identidock:
    image: amouat/identidock:1.0
    links:
      - dnmonster
      - redis
    environment:
      ENV: PROD
  dnmonster:
    image: amouat/dnmonster
  redis:
    image: redis:7.0.4

  logstash:
    image: logstash:1.5
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
#    volumes:
#      - ./logstash.conf:/etc/logstash.conf
    environment:
      LOGSPOUT: ignore
#    links:
#      - elasticsearch
    ports:
      - "127.0.0.1:5544:5544"
      - "8080:90"
#    command: -f /etc/logstash.conf
