version: "3.3"
services:

  proxy:
    container_name: proxy
    image: sh1nd3l/proxy:0.1
    restart: always
    logging:
      driver: syslog
      options:
        syslog-address: udp://localhost:5000
    links:
      - server
    ports:
      - "80:80"
    depends_on:
      - logstash

  server:
    image: sh1nd3l/flask-server:0.5
    container_name: flask
    environment:
      - "ENV=PROD"
    links:
      - redis
      - dnmonster

  redis:
    container_name: redis
    image: redis:7.0.4
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  dnmonster:
    container_name: dnmonster
    image: amouat/dnmonster

  logstash:
    image: logstash:6.4.0
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    container_name: logstash
    ports:
      - "5000:5000"
