node {
    // Clone the configurations repository
    stage('Clone') { // for display purposes
        cleanWs()
        git 'https://github.com/LinkedInLearning/advanced-terraform-2823489.git'
    }

    // Download Terraform
    stage('Download') {
        sh label: '', script: 'curl https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip \
            --output terraform_0.12.29_darwin_amd64.zip \
             && unzip terraform_0.12.29_darwin_amd64.zip'
    }

    // Initialize the Terraform configuration
    stage('Backend-Init') {
        dir('03_01_remotestate/remote_resources') {
            sh script: '../../terraform init -input=false'
        }

    }

    // Create Terraform plan for backend resources
    stage('Backend-Plan') {
        withCredentials([string(credentialsId: 'AWS_ACCESS_KEY', variable: 'aws_access_key'),
                        string(credentialsId: 'AWS_SECRET_KEY', variable: 'aws_secret_key')]) {
            dir('03_01_remotestate/remote_resources') {
                sh script: '../../terraform plan \
                        -out=backend.tfplan \
                        -var="aws_access_key=$aws_access_key" \
                        -var="aws_secret_key=$aws_secret_key"'
            }
        }
    }
    // Apply terraform plan
     stage('Backend-Apply') {
        withCredentials([string(credentialsId: 'AWS_ACCESS_KEY', variable: 'aws_access_key'),
                            string(credentialsId: 'AWS_SECRET_KEY', variable: 'aws_secret_key')]) {
            dir('dir_name') {
                sh script: '../../terraform apply plan_name.tfplan \
                            -var="aws_access_key=$aws_access_key" \
                            -var="aws_secret_key=$aws_secret_key"'
            }
        }
     }
    // Destroy by terraform
        stage('Backend-Destroy'){
        input 'Destroy?'
        withCredentials([string(credentialsId: 'AWS_ACCESS_KEY', variable: 'aws_access_key'),
                        string(credentialsId: 'AWS_SECRET_KEY', variable: 'aws_secret_key')]) {
            dir('03_01_remotestate') {
                sh script: '../terraform destroy \
                        -auto-approve \
                        -var="aws_access_key=$aws_access_key" \
                        -var="aws_secret_key=$aws_secret_key"'
            }
            dir('03_01_remotestate/remote_resources') {
                sh script: '../../terraform destroy \
                        -auto-approve \
                        -var="aws_access_key=$aws_access_key" \
                        -var="aws_secret_key=$aws_secret_key"'
            }
        }
    }
    }

}