version: "3.3"
services:

  proxy:
    container_name: proxy
    image: sh1nd3l/proxy:0.1
    restart: always
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5000
    links:
      - server
    ports:
      - "80:80"
    depends_on:
      - logstash

  server:
    image: sh1nd3l/flask-server:0.5
    container_name: flask
    depends_on:
      - logstash
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5000
    environment:
      - "ENV=PROD"
    links:
      - redis
      - dnmonster
  redis:
    container_name: redis
    image: redis:7.0.4
    depends_on:
      - logstash
    logging:
      driver: syslog
      options:
        syslog-address: tcp://localhost:5000

  dnmonster:
    container_name: dnmonster
    image: amouat/dnmonster

  logstash:
    build: .
    container_name: logstash
    depends_on:
      - elasticsearch
    restart: always
    environment:
      LOGSPOUT: ignore
    ports:
      - "5000:5000"
    links:
      - elasticsearch

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:6.4.0
    volumes:
      - ./elk.conf.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      LOGSPOUT: ignore
        - http.host=0.0.0.0
        - transport.host=0.0.0.0
        - "ES_JAVA_OPTS=-Xms1g -Xmx1g "
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:6.4.0
    container_name: kibana
    environment:
      LOGSPOUT: ignore
      ELASTICSEARCH_URL: http://elasticsearch:9200
    links:
      - elasticsearch
    ports:
      - "5601:5601"