services:
  server:
    build: .
    ports:
      - "80:80"
      - "81:81"
    environment:
      ENV: DEV
    volumes:
      - ./app:/opt/app
    links:
      - dnmonster
      - redis

  dnmonster:
    image: amouat/dnmonster:1.0
  redis:
    image: redis:3.0